[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[git_branch]
symbol = ""
format = '[$symbol $branch ]($style)'

[python]
symbol = "󰌠 "
style = "fg:#4B8BBE"
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[java]
format = '[${symbol}(${version} )]($style)'

[gradle]
symbol = " "
format = '[$symbol($version )]($style)'

[kotlin]
symbol = " "
format = '[$symbol($version )]($style)'

[golang]
symbol = " "
format = '[$symbol($version )]($style)'

[rust]
symbol = "󱘗 "
format = '[$symbol($version )]($style)'
